export const CSS_ACTIVE_HABDLE = "CSS_ACTIVE_HABDLE";
export const CLOSE_BUTTON_HANDLE = "CLOSE_BUTTON_HANDLE";
export const HANDLE_LOADING_SCREEN = "HANDLE_LOADING_SCREEN";
export const HANDLE_EDITTING = "HANDLE_EDITTING";
export const HANDLE_UPDATE_LOADING = "HANDLE_UPDATE_LOADING";