export const HANDLE_EXCELFILE_INPUT = "HANDLE_EXCELFILE_INPUT";
export const STORE_VALUE_TO_STATA = "STORE_VALUE_TO_STATA";
export const POST_DATA_TO_NODEJS= "POST_DATA_TO_NODEJS";
export const CALL_API_GET_DATA = "CALL_API_GET_DATA";
export const SET_CROODS = "SET_CROODS";